#!/bin/bash

_runcBinary="/usr/local/bin/docker-runc-original"
_argArray=( "$@" )
_straceCmd="strace -f -s 1024 -v -o "

_ID="${_argArray[-1]}"
_STRACE=0

function contains() {
    local n=$#
    local value=${!n}
    for ((i=1;i < $#;i++)) {
        if [ "${!i}" == "${value}" ]; then
            echo "y"
            return 0
        fi
    }
    echo "n"
    return 1
}

# if this is a request to start a container..
contains "${_argArray[@]}" "start" && [ "${STRACE_RUNC}" -eq 1 ] && {
  echo Executing strace for ID=${_ID} >>/tmp/runc.log
  _STRACE=1
}

# execute the real runc, potentially capturing strace if requested
if [ "${_STRACE}" -eq 1 ]; then
  exec ${_straceCmd} "/tmp/strace-${_ID}.log" ${_runcBinary} $@
else
  exec ${_runcBinary} $@
fi
